<a href="https://www.kaggle.com/code/bibekrai/neural-network?scriptVersionId=293851371" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
input = [1,2,3,2.5]
weight1 = [0.2,0.8,-0.5,1.0]
weight2 = [0.5,-0.91,0.26,-0.5]
weight3 = [-0.26,-0.27,0.17,0.87]
bias1 = 2
bias2 = 3
bias3 = 0.5

output = [input[0]*weight1[0] + input[1]*weight1[1] + input[2]*weight1[2] + input[3]*weight1[3] + bias1,
          input[0]*weight2[0] + input[1]*weight2[1] + input[2]*weight2[2] + input[3]*weight2[3] + bias2,
          input[0]*weight3[0] + input[1]*weight3[1] + input[2]*weight3[2] + input[3]*weight3[3] + bias3]
print(output)

[4.8, 1.21, 2.385]


In [3]:
import numpy as np
input = [1,2,3,2.5]
weights = [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]

bias = [2,3,0.5]

output = np.dot(weights,input) + bias

print(output)

[4.8   1.21  2.385]


In [4]:
input4 = [[1.0,2.0,3.0,2.5],
         [2.0,5.0,-1.0,2.0],
         [-1.5,2.7,3.3,-0.8]]

weights5 = [[0.1,-0.14,0.5],
            [-0.5,-0.12,-0.33],
            [-0.44,0.73,-0.13]]
weights4 = [[0.2,0.8,-0.5,1.0],
            [0.5,-0.91,0.26,-0.5],
            [-0.26,-0.27,0.17,0.87]]
bias4 = [2,3,0.5]
bias5 = [-1,2,-0.5]

#transposing matrix

layer1_output = np.dot(input4,np.array(weights4).T ) + bias4
layer2_output = np.dot(layer1_output,np.array(weights5).T) + bias5
print(layer1_output)
print(layer2_output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
[[ 0.5031  -1.33225 -2.03875]
 [ 0.2434  -2.2988  -5.7633 ]
 [-0.99314  1.1603  -0.35655]]


In [5]:
X = [[1.0,2.0,3.0,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8]]

np.random.seed(0)

class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs,n_neurons)
        self.biases = np.zeros((1,n_neurons))
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.biases

layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]
[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
